const books = [
    {
        id:1,
        title: "The King of Drugs", 
        authors: ["John Resig"], 
        publishedDate: "2010-9-10",
        price: "4.00",
        started: false,
        condition: "good",
        department: "Art",
        for: "sale",
        image: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/action-thriller-book-cover-design-template-3675ae3e3ac7ee095fc793ab61b812cc_screen.jpg?ts=1588152105",
        description: "",
    },
    {
        id:2,
        title: "Guy Kawasaki", 
        authors: ["John Resig"], 
        publishedDate: "2010-9-10",
        price: "2.90",
        started: true,
        condition: "excellent",
        department: "Art",
        for: "sale",
        image: "https://www.creativindie.com/wp-content/uploads/2013/10/Enchantment-Book-Cover-Best-Seller1.jpg",
        description: "",
    },
    {
        id:3,
        title: "Making Things Happen", 
        authors: ["John Resig"], 
        publishedDate: "2010-9-10",
        price: "8.30",
        started: false,
        condition: "good",
        department: "Communication",
        for: "sale",
        image: "https://www.themaddesigntist.com/wp-content/uploads/2018/04/business_bookcover-1.png",
        description: "",
    },
    {
        id:4,
        title: "The Workings of A Business", 
        authors: ["John Resig"], 
        publishedDate: "2010-9-10",
        price: "9.30",
        started: true,
        condition: "not bad",
        department: "Business",
        for: "rent",
        image: "https://cdn.cp.adobe.io/content/2/rendition/0ce69ff9-b2a7-4e2e-9cbe-43e1fd2575c3/artwork/f32f3a60-95b2-4bfd-b415-d8e52a9f6999/version/0/format/jpg/dimension/width/size/300",
        description: "",
    },
    {
        id:5,
        title: "Algorithm and JAVA", 
        authors: ["John Resig"], 
        publishedDate: "2010-9-10",
        price: "13.20",
        started: false,
        condition: "poor",
        department: "Business",
        for: "sale",
        image: "https://www.creativindie.com/wp-content/uploads/2013/10/Enchantment-Book-Cover-Best-Seller1.jpg",
        description: "",
    },
    {
        id:6,
        title: "Algorithm and JAVA", 
        authors: ["John Resig"], 
        publishedDate: "2010-9-10",
        price: "5.00",
        started: false,
        condition: "good",
        department: "Business",
        for: "rent",
        image: "https://www.creativindie.com/wp-content/uploads/2013/10/Enchantment-Book-Cover-Best-Seller1.jpg",
        description: "",
    },
    {
        id:7,
        title: "Algorithm and JAVA", 
        authors: ["John Resig"], 
        publishedDate: "2010-9-10",
        price: "10.00",
        started: false,
        condition: "excellent",
        department: "Business",
        for: "sale",
        image: "https://www.creativindie.com/wp-content/uploads/2013/10/Enchantment-Book-Cover-Best-Seller1.jpg",
        description: "",
    },
    {
        id:8,
        title: "Algorithm and JAVA", 
        authors: ["John Resig"], 
        publishedDate: "2010-9-10",
        price: "17.50",
        started: false,
        condition: "good",
        department: "Business",
        for: "rent",
        image: "https://www.creativindie.com/wp-content/uploads/2013/10/Enchantment-Book-Cover-Best-Seller1.jpg",
        description: "",
    },
];

export default books;